### ISSUE TITLE
the tripadvisor_spider.py doesn't work

### ISSUE THREAD

**Issue by mmcgithub** [monkeylearn/hotel-review-analysis#7]
When the spider open, it doesn't crawl any pages. Any thoughts?
Mind sharing some clue when creating the spider?

[scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)

**Comment by brusteca** [comment]
Sorry about this. TripAdvisor and Booking.com have changed their sites greatly since these spiders were written, and as such, they no longer work. We will probably fix them in the future (it looks as though changing the selectors should be enough) but it's not in our short term plans, sadly.

**Comment by mmcgithub** [comment]
Good to know. Thanks for the quick response. It does feel like it is not
about the code side, but the "source side"
